### ISSUE TITLE
Observed failures in the execution of two scripts

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#113] opened 2020-03-21 21:50 UTC
I have observed errors in the execution of two scripts, these are not saved in the log, and I cannot determine what is causing them, so I pass you two screenshots in case they are useful.

Script error 1:

![fallo_script1](https://user-images.githubusercontent.com/2179224/77237180-367bc880-6bc6-11ea-8b2e-a23824e8692b.PNG)

This may have to do with the tutorial not running correctly, but I'll open an issue about it.

Script error 2:

![fallo_script2](https://user-images.githubusercontent.com/2179224/77237190-3f6c9a00-6bc6-11ea-876b-6fa0ee66e32f.PNG)

Regards

**Comment by scemino** [comment] 2020-03-22 08:35
The first script error is easy to reproduce, but the second one... how can I reproduce it ?

**Comment by Mac1512** [comment] 2020-03-22 17:06
The second error has only given me once and I do not know how to reproduce it again, perhaps it is a point error.

The fact is, I was driving actor Ray or Reyes, where the body was in the Bridge room, when that bug came out. I know I tried many options or else with the body, poster, light ... I don't know, since when I realized it, it had come out. Perhaps I would have blocked the console window to capture the first failure and then this one came out ... or it was for any other reason, since I have not been able to reproduce it again in new tests that I have carried out.

So at the moment I can not be of help in the face of this failure, if in the future I see it again, I will comment here.

**Comment by Mac1512** [comment] 2020-03-22 17:21
I have seen that with this commit:

Fix findScreenPosition called with an object as argument https://github.com/scemino/engge/commit/ffcfb38020fc855ca05464c7f1cc949881772732

This error has occurred:

![fail_double_screen](https://user-images.githubusercontent.com/2179224/77255726-dd657080-6c69-11ea-815f-721f3c4e0792.PNG)

**Comment by Mac1512** [comment] 2020-03-22 18:13
What I said in the previous post, is resolved in this commit, although many other failures arise, such as, One actor cannot give an object to another, the height of the texts that the actors say is now incorrect, it has also been generated new layer errors. For example:

![fallo_layer_interior_sheriff](https://user-images.githubusercontent.com/2179224/77256890-2a991080-6c71-11ea-9086-0efaa62bb4ac.PNG)

Now willie if he snores, you see the text and you hear him snore, although his head blinks and he continues to see the text "snore" even if Boris advances to the right and stops seeing Willie.

I guess maybe part of these bugs you already know, so I'll wait for new commits, before opening new issues

**Comment by scemino** [comment] 2020-03-24 14:29
If you agree, I can close this issue, the first script error has been fixed (and the regression) and I can't reproduce the second script error.
If it happens again, just open a new issue.

**Closed** 2020-03-24 18:56 UTC
Labels: bug

**Comment by Mac1512** [comment] 2020-03-24 19:05
Yes, I think it is the right thing to do. If this error appears again, it will reopen an issue
