### ISSUE TITLE
engge closes unexpectedly when accessing the options menu or saving game, normally the second time

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#167] opened 2020-05-30 22:56 UTC
**Describe the bug**

engge closes unexpectedly when accessing the options menu or saving game, normally the second time

**To Reproduce**

Testing the commit:

Fix call a callback when exiting elevator (https://github.com/scemino/engge/commit/aeb37dae999a0187eb837858dd4839b22ee7ec93)

engge closes unexpectedly when accessing options or when saving a game, usually the second time, when I try to open the options menu or when saving in a new slot. This I tested at the beginning, part 1, managing Boris. I saved the game after crossing the door, and when saving again in the same area, engge has closed unexpectedly, no error is observed in the log.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Version 10

**Additional context**

**Comment by scemino** [comment] 2020-05-31 13:01
I can't reproduce it, did you try to remove (or just move in other directory) your savegames? Maybe it comes from a 1 or more corrupted savegames, if it comes from a savegame, can you send it to me, I will try to fix the issue correctly.
Thank you.

**Comment by Mac1512** [comment] 2020-06-01 15:34
> 
> 
> I can't reproduce it, did you try to remove (or just move in other directory) your savegames? Maybe it comes from a 1 or more corrupted savegames, if it comes from a savegame, can you send it to me, I will try to fix the issue correctly.
> Thank you.

You are right, the problem is due to a saved game ... maybe some data was corrupted when saving it. I think that when there is a failure a json of the saved game is generated, right?

I have moved the saved games to another location and the problem has been resolved. However, I am sending you the saved games so you can keep an eye on them.

Link:

https://www.mediafire.com/file/nk8ttvmq07eiw01/engge-0.5.0-alpha-win32-saves_fail.7z/file

Cheers :)

**Comment by scemino** [comment] 2020-06-01 18:40
With the commit aeb37da, if I load the second savegame you gave me I can reproduce a crash when moving Boris to the body, I can reproduce it each time. With the last commit b0bdea3, there is no crash. So I close this issue if you agree.

**Closed by scemino** 2020-06-01 18:40 UTC

**Comment by Mac1512** [comment] 2020-06-02 19:15
I see it correct :)
